### ISSUE TITLE
Cannot Exclude bcdboot.exe (Packaged with Dism++ Portable v10.1.1002.1) in UCheck BETA v5.0.7.0

### ISSUE THREAD

**Issue by ljmacri** [AdliceSoftware/UCheck#14]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

I am unable to exclude files named **bcdboot.exe** that are included with with Dism++ Portable v10.1.1002.1 (rel. 26-Mar-2023).  The exclusion appears to be successful but the files re-appear in the UCheck interface the next time UCheck is launched.

Please note this problem was previously documented for UCheck BETA v5.0.5.0 (rel. 08-Nov-2023) at https://www.wilderssecurity.com/threads/ucheck-update-your-software-in-2-clicks.404593/page-37#post-3171150 in the Wilders Security forum.

To reproduce the problem:

1. Download Dism++ Portable v10.1.1002.1B (Dism++10.1.1002.1B.zip from MajorGeeks (https://www.majorgeeks.com/files/details/dism.html) or Chuyu-Team's GitHub page (https://github.com/Chuyu-Team/Dism-Multi-language), save to removable USB stick (e.g., E:\Portable\Dism 10_1_1002) and unzip.
2. Delete Dism++10.1.1002.1B.zip after packaged files have been unzipped and ensure Dism++ launches correctly (e.g., double-click Dism++x64.exe for 64-bit Windows machine).
3. Launch UCheck BETA v5.0.7.0 (rel. 05-Dec-2023) as Administrator and run scan from main dashboard.
4. Go to Installed | Portable tab, right-click on either **bcdboot.exe** file named Microsoft Windows Operating System (e.g., E:\Portable\Dism 10_1_1002\Config\x86\bcdboot.exe) and choose **Exclude Software** from context menu (see image A).
5. Answer Yes to prompt "_Are you sure you want to exclude this program?_" (see image B);  will see confirmation stating "_Exclusion added with success_" (see image C).  Click OK to close confirmation.
6. Go to Settings & History | Exclusions and confirm Microsoft Windows Operating System is listed in the exclusions (see image D). 
7.  Close UCheck.
8. Re-launch UCheck as Administrator and run new scan. **Previously excluded bdcboot.exe file still appears on Installed | Portable tab** (see image E) and **Microsoft Windows Operating System is no longer listed at Settings & History | Exclusions** (see image F).

![A- UCheck BETA v5_0_7_0 Portable Exclude Dism v10_1_1002 bcdboot_exe 07 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/2f7511e4-3fb1-4ef7-b4ca-5d9a5fa41bd8)
![B - UCheck BETA v5_0_7_0 Confirm Yes No Exlude Dism 10_1_1002 bcdboot_exe 07 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/04a32364-b0de-4179-8cd9-f95e65cdbeac)
![C - UCheck BETA v5_0_7_0 Dism 10_1_1002 bcdboot_exe Exclusion Added With Success 07 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/226804e9-57f2-4c38-a8ac-57cad250b52d)
![D - UCheck BETA v5_0_7_0  Settings Exclusions MS Windows OS Listed 07 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/3cecc8a7-3fd1-4bf0-8cc0-8a545326b227)
![E - UCheck BETA v5_0_7_0  Re-Scan Installed Portable Dism bcdboot_exe Not Excluded 07 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/2b094af1-9741-4d5d-8821-0e5b2517086c)
![F - UCheck BETA v5_0_7_0  Re-Scan Settings Exclusion Dism bcdboot_exe Missing 07 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/9bc04676-0aa0-461f-b9a8-6c75b9b2891e)

### ucheck-report

Attached .TXT file is excerpt of debug log at C:\ProgramData\UCheck\Debug\UCheck_debug.log for all scans from 07-Dec-2023 (date of test).

[UCheck_debug log 07 Dec 2023.txt](https://github.com/AdliceSoftware/UCheck/files/13601943/UCheck_debug.log.07.Dec.2023.txt)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Thanks, bug is fixed for next version.

**Comment by ljmacri** [comment]
The latest bug fix in UCheck BETA-2 v5.0.7.0 (rel. 15-Dec-2023) that adds exclusions based on file / folder / program has partially solved the problem for exclusions my Dism++ Portable v10.1.1002.1B app located on a removable USB stick at E:\Portable\Dism 10_1_1002.  I am now able to exclude folders and programs but **I am still not able to exclude individual files based on their file name**.

For example, I excluded the entire **E:\Portable\Dism 10_1_1002\Config** folder (choosing Exclude This Path - see image A) with the latest UCheck BETA-2 v5.0.7.0 (run as Administrator) ...

![A- UCheck BETA-2 v5_0_7_0 Portable Exclude Path Dism Config Folder 16 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/51f0cee5-e008-4f51-b594-66bc95a910bb)

... and then excluded all executables in E:\Portable\Dism 10_1_1002 **except Dism++64.exe** (choosing Exclude Software - see image B).

![B- UCheck BETA-2 v5_0_7_0 Portable Exclude Software Unused Dism Executables 16 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/aff72f24-41cf-4eda-b5b0-900c95fef479)

This image shows the final result where entire E:\Portable\Dism 10_1_1002\Config and two executables (Dism++ARM64.exe and Dism++x86.exe) were marked as excluded with the prefix "**[E]**"  but Dism++x64.exe was not (see image C).

![C - UCheck BETA-2 v5_0_7_0 Portable Excluded Dism Folder and Executables 16 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/15484718-1afd-49d8-b886-5a2b190a8fbf)

All three Dism++ executables (Dism++ARM64.exe, Dism++x64.exe and Dism++x86.exe) share the **same Product Name** "Dism++" in their file properties and the UCheck Exclusions at History & Settings | Exclusions suggested that all three Dism++ executables, including Dism++x64.exe, had been excluded (see image D). This was confirmed after UCheck BETA-2 v5.0.7.0 was restarted and a fesh scan showed that none of the executables for Dism++ was displayed on the Portable tab. (see image E).

![D - UCheck BETA-2 v5_0_7_0 Settings Initial Exclusions for Dism 16 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/8ca1f344-5632-46f2-b63b-e2b44a9c3273)

![E - UCheck BETA-2 v5_0_7_0 Portable After 1st Restart Dism++x64_exe Missing Dism 16 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/4be6a8ae-d7d1-4669-bb26-b167933263af)
_______________________________________________

To fix this problem I had to **remove the exclusion for dism++ (all versions)** at History & Settings | Exclusions while leaving the exclusion for the E:\Portable\Dism 10_1_1002\Config in place (see image F) and then **manually delete the "unwanted" Dism++ARM64.exe and and Dism++x86.exe executable files** in E:\Portable\Dism 10_1_1002 using File Explorer (see image G).  Upon restarting and running a fresh scan, UCheck BETA-2 v5.0.7.0 now correctly displays information for the single **Dism++x64.exe** executable (see image H).

![F - UCheck BETA-2 v5_0_7_0 Settings Exclusions Dism Config Folder Only 16 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/f6c5b7dc-8050-4d74-b5e9-08ba284b8f5d)

![G - Win 10 Pro v22H2 File Explorer Delete Unwanted Dism Executables 16 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/03fca4fe-0e44-47d8-a2d4-22bec110b3bb)

![H - UCheck BETA-2 v5_0_7_0 Portable After 2nd Restart Dism++x64_exe Visible 16 Dec 2023](https://github.com/AdliceSoftware/UCheck/assets/145856101/d8cb4bdf-9fa7-4202-b0e8-f745caeab031)

The following attachments are  the UCheck BETA-2 v5.0.7.0 **scan log** and **debug log** for a scan started 16-Dec-2023 @ 10:36 AM with my final exclusions (i.e., only showing the single Dism++x64.exe executable in the UCheck interface).

[UCheck BETA-2 v5_0_7_0 Scan Log 16 Dec 2023.txt](https://github.com/AdliceSoftware/UCheck/files/13693256/UCheck.BETA-2.v5_0_7_0.Scan.Log.16.Dec.2023.txt)
[UCheck BETA-2 v5_0_7_0 Debug Log 16 Dec 2023.txt](https://github.com/AdliceSoftware/UCheck/files/13693257/UCheck.BETA-2.v5_0_7_0.Debug.Log.16.Dec.2023.txt)

**Comment by Tigzy** [comment]
After excluding a folder, you need to redo a scan for the change to appear. 
This is how it works: 
- File exclusions will still display the files, as there's no benefits hiding them. 
- Folder exclusions will NOT ITERATE into the folder to lookup for files, hence speeding up the scan. This is why the folder isn't displayed starting the next scan. 

To remove folder exclusion, since it's not any longer in the results, it has to be done in the Exclusions settings.
Implemented in 5.1
