### ISSUE TITLE
UCheck v5.5.0.0-BETA2 - Four Issues

### ISSUE THREAD

**Issue by ljmacri** [AdliceSoftware/UCheck#52]
### Preliminary Checks

- [X] I use a modern operating system (Windows 7 with SP1 or newer)
- [X] I use the latest version of UCheck available (stable or beta version)
- [X] I checked that the issue I'm reporting was not already reported

### Beta Version

- [X] I am reporting an issue for UCheck BETA

### What happened?

I have a Win 10 Pro v22H2 laptop and am running the latest v5.5.0.0-BETA2 (released 31-May-2024) from a removable USB stick. 

I have found multiple issues with UCheck v5.5.0.0-BETA2. Most of these problems are related to **winget scanning** and could likely be solved if UCheck behaved like the previous UCheck v5.3.1.0 (i.e., if "Winget" apps were re-classified as "Community" apps) when winget scanning at History & Settings | Scan Settings | Winget | Scan for Updates Using Winget was turned OFF).

**Problem 1: Pre-Loading Previous Scan at Launch Can Display Outdated Information**

Pre-loading data for the previous scan when UCheck v5.5.0.0-BETA2 is launched often displays incorrect (outdated) version information, especially for users with a large number of "Community" and portable apps who cannot update most of their outdated software from the UCheck interface.  Waiting for this outdated data to load wastes time and this feature should be removed.

Here's a test I ran yesterday with UCheck v5.5.0.0-BETA2:

1. Clicked SCAN on dashboard, first scan correctly showed MS Edge v125.0.2535.67 browser (rel. 24-May-2024) needed to be updated to v125.0.2535.79 (rel. 30-May-2024).
2. Closed UCheck, launched MS Edge and went to More | Help and Feedback | About Microsoft Edge to update MS Edge to latest v125.0.2535.79.
3. Launched UCheck, previous scan results loaded which **incorrectly showed the old MS Edge v125.0.2535.67 was installed and still needed to be updated**.

**Problem 2: Tunring OFF Winget Scanning Changes the Status of Outdated Winget Apps to "Latest"**

For example, if I click SCAN on the dashboard when History & Settings | Scan Settings | Winget | **Scan for Updates Using Winget is turned ON** then UCheck v5.5.0.0-BETA2 correctly shows my Windows PC Health Check v3.6.2204.08001 app is a "Winget" app with a Status of "Outdated".

![A - UCheck v5_5_0_0 BETA2 Winget Scanning ON Two Updates 31 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/3ad41bc7-25aa-4a62-ba34-31bf38aea008)

![B - UCheck v5_5_0_0 BETA2 Winget Scanning ON Win PC Health Check Outdated 31 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/069f5da3-4c8d-4a0d-b310-edaa2d4e9f9b)

If History & Settings | Scan Settings | Winget | **Scan for Updates Using Winget is turned OFF** the Status of Windows PC Health Check v3.6.2204.08001 simply changes  to "Latest" even though a newer v3.7.2204.15001 is still detected.

![C - UCheck v5_5_0_0 BETA2 Winget Scanning OFF One Update 31 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/02140f41-6853-46ed-8097-98d86ddc600b)

![D - UCheck v5_5_0_0 BETA2 Winget Scanning OFF Win PC Health Check Latest 31 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/7dbaa0fe-8cd5-4d56-a041-eaa2e40f488b)

This looks like a "cheat" to fix Issue https://github.com/AdliceSoftware/UCheck/issues/50 (_Multiple Microsoft Apps Change to "Unsupported" When Winget is Disabled in UCheck v5.4.0.0_) but it does not address the root cause of the problem - that **many outdated apps will go undetected if winget scanning is disabled in the settings**. 

As previously noted, it would be much better if turning off winget scanning simply reverted "Winget" apps back to "Community" apps so outdated software could be detected based on telemetry collected from the community.  If that isn't possible then winget scanning should be completely removed from the upcoming stable release of UCheck v5.5.0.0, all Winget apps should be hidden from view on the UCheck Installed tab when winget scanning is disabled,  or the ability to turn OFF winget scanning should be removed from the settings.

**Problem 3: AdwCleaner (Portable) Has Changed from "Compatible" to "Unsupported"**

Previous versions of UCheck have always classified AdwCleaner v8.x (a fully portable .exe file that can be run from a removable USB stick) as a fully supported "Compatible" app.  UCheck v5.5.0.0-BETA2 now classifies AdwCleaner v8.x as "Unsupported".

From UCheck v5.4.0.0 :

![E - UCheck v5_4_0_0 Portable Apps AdwCleaner Compatible 01 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/e5e7136f-35d6-4e08-8481-1ef160a072fa)

From UCheck v5.5.0.0-BETA2 :

![F - UCheck v5_5_0_0 BETA2 Portable Apps AdwCleaner Unsupported 31 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/4257b958-a50b-4ac2-94bf-0a4470b187e7)

**Problem 4: Installed "Winget" Apps With Longer Program Names Are Now "Unsupported"**

From UCheck v5.4.0.0 :

![G - UCheck v5_4_0_0 Winget Apps With Longer Names Ssupported 01 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/e3910538-8468-46b2-b2d8-9ca1f6a83b95)

From UCheck v5.5.0.0-BETA2 :

![H - UCheck v5_5_0_0 BETA2 Winget Apps With Longer Names Unsupported 31 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/71a18b1e-5bd0-4e2f-ade6-3a94c754707f)

UCheck v5.4.0.0 was able to correctly classify winget-supported apps with longer names as "Winget" and find available updates, so I am not sure why the winget issue at https://github.com/microsoft/winget-cli/issues/1653 that dates back to 27-Oct-2021 has been referenced as the reason why these apps are now "Unsupported" in UCheck v5.5.0.0-BETA2.

When UCheck is looking up Winget apps is it trying to match according to the longer winget NAME [e.g., Microsoft Windows Desktop Runtime - 8.0.6 (64x)] instead of the **shorter ID** (e.g., Microsoft.DotNet.DesktopRuntime.8)?

------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4412 * Firefox v126.0.1 * Microsoft Defender v4.18.24040.4 -1.1.24050.5 * Malwarebytes Premium v5.1.4.112-1.0.1244 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck v5.5.0.0-BETA1

### ucheck-report

Sample logs for UCheck v5.5.0.0-BETA2 with Winget scanning ON (2 apps outdated):

[Winget Scanning ON Scan Log 01 Jun 2024.txt](https://github.com/user-attachments/files/15522024/Winget.Scanning.ON.Scan.Log.01.Jun.2024.txt)
[Winget Scanning ON Debug Log 01 Jun 2024.txt](https://github.com/user-attachments/files/15522026/Winget.Scanning.ON.Debug.Log.01.Jun.2024.txt)

Sample logs for UCheck v5.5.0.0-BETA2 with Winget scanning OFF (1 app outdated):

[Winget Scanning OFF Scan Log 01 Jun 2024.txt](https://github.com/user-attachments/files/15522028/Winget.Scanning.OFF.Scan.Log.01.Jun.2024.txt)
[Winget Scanning OFF Debug Log 01 Jun 2024.txt](https://github.com/user-attachments/files/15522030/Winget.Scanning.OFF.Debug.Log.01.Jun.2024.txt)

### Is the issue reproductible?

Yes

### Don't forget to vote !

- [X] Bugs and new features will be treated by priority and popularity.
Make sure **you vote below** with a :thumbsup: !

**Comment by Tigzy** [comment]
Hi,
Problem 1/ I'm not sure to understand the problem here.
Yes loading last scan data can show wrong information if you update some software in between. 
It would be exactly the same if you leave UCheck opened and update outside of it. 

Information will not be refreshed until you do a new scan, or if you click on "Refresh data" on the items you wish to verify.

**Comment by Tigzy** [comment]
Problem 2/ I'm not sure to understand the problem either, are you re-running a scan after you turn OFF Winget ? Or is it when you do a reload of the app ?

**Comment by Tigzy** [comment]
Problem 3/ Found and fixed, thanks.

**Comment by Tigzy** [comment]
Problem 4/ looks normal to me, for several reasons: 

1/ We have now globally excluded all VC++ from Community, due to many false positives.
2/ As explained [here](https://www.wilderssecurity.com/threads/ucheck-update-your-software-in-2-clicks.404593/page-60#post-3197394): 

```
Please note because of this Winget issue https://github.com/microsoft/winget-cli/issues/1653 (lots of people complaining, hopefully they do something)
we had to NOT support some of the programs if they have a long name and if there's a similar one on the same machine, for example:

- "Very very long name that would result in Winget truncating the end of it version x86"
- "Very very long name that would result in Winget truncating the end of it version x64"

UCheck would see something like

- "Very very long name that would result in Winget truncating the end..."
- "Very very long name that would result in Winget truncating the end..."

And would not be able to know which one is what, therefore we decided to drop Winget information in this case.
It should be minor cases, but I know for sure most of the Microsoft C++ detections are in this situation.
```

**Comment by ljmacri** [comment]
> Hi, Problem 1/ I'm not sure to understand the problem here. Yes loading last scan data can show wrong information if you update some software in between.

Hi Tigzy:

Loading data from the previous scan is **slow**, particularly during the step where it lists all the portable programs I run from a removable USB stick.  I would much rather just launch UCheck and immediately click SCAN to start a new scan instead of waiting 10 or 15 seconds waiting for **outdated** data from the previous scan to load.

Note that the image below showing data loading from the previous scan was captured with v5.5.0.0-BETA3 (released 03-Jun-2024).

![UCheck v5_5_0_0 BETA3 Load of Previous Scan Slow 03 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/27f042b3-9a7e-4078-82c8-9abbbdafcfec)

**Comment by ljmacri** [comment]
> Problem 2/ I'm not sure to understand the problem either, are you re-running a scan after you turn OFF Winget ? Or is it when you do a reload of the app ?

Hi Tigzy:

Steps followed for problem # 2:

1. Launched UCheck and ran a new scan with History & Settings | Scan Settings | Winget | Scan for Updates Using Winget turned ON (the default). _Captured first set of images_.
2. Turned OFF the setting at History & Settings | Scan Settings | Winget | Scan for Updates Using Winget.
3. Closed UCheck.
4. Re-launched UCheck and ran a new scan. _Captured second set of images_.

**Comment by ljmacri** [comment]
> Problem 3/ Found and fixed, thanks.

Just an FYI that my AdwCleaner v8.x portable app is still "Unsupported" in UCheck v5.5.0.0-BETA3 (rel. 03-Jun-2024).

![UCheck v5_5_0_0 BETA3 Portable Apps AdwCleaner Unsupported 03 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/3633018c-46c6-441a-ac55-a461c82fb9c8)

**Comment by ljmacri** [comment]
> Problem 4/ looks normal to me, for several reasons:
> 
> 1/ We have now globally excluded all VC++ from Community, due to many false positives.

Hi Tigzy:

My main concern is that your global exclusion of Winget apps with "long names" goes beyond the Microsoft Visual C++ Redistributables.  For example, it looks like my Winget app **Microsoft Windows Desktop Runtime - 8.0.x** (ID = Microsoft.DotNet.DesktopRuntime.8) has also been globally excluded.

Note that the image below was captured with v5.5.0.0-BETA3 (released 03-Jun-2024).

![UCheck v5_5_0_0 BETA3 Winget Apps With Longer Names Unsupported NET v8_x 03 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/12aaf794-b645-4616-a959-1105dfff3989)

No worries, though. My QuickInstaller app (https://www.quickinstaller.net/) still seems to be able to handle these Winget apps with "long names" correctly.

![QuickInstaller v0_3_8859_20616 Winget Apps With Longer Names OK 31 May 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/2722a897-7332-468e-a63a-45e130f0cbb1)

**Comment by Tigzy** [comment]
/1 You don't seem to have a lot in portable locations, and I think 10 seconds isn't too much compared to a real scan... Could you let me know how much time it takes for the regular scan ? We'll maybe consider making a setting for scan reloading. 
2/ EDIT: found and fixed.
3/ You need to re-launch a scan for it to show supported, your old scan data is outdated.
4/ Could you find that piece of software in the logs and tell me what it said ?

**Comment by ljmacri** [comment]
> /1 You don't seem to have a lot in portable locations, and I think 10 seconds isn't too much compared to a real scan... Could you let me know how much time it takes for the regular scan ? We'll maybe consider making a setting for scan reloading.
 2/ EDIT: found and fixed.
 3/ You need to re-launch a scan for it to show supported, your old scan data is outdated.
 4/ Could you find that piece of software in the logs and tell me what it said ?

Hi Tigzy:

Problems 1, 2, and 3 are fixed in the latest **UCheck v5.5.0.0-BETA4** (rel. 04-Jun-2024) if UCheck is set to run a new scan when the program starts.

**Problem 1**: FIXED - Scans are much more consistent when the new setting at History & Settings | General | Auto-Scan is set to Automatically Launch a Scan When Application Starts. _**NOTE**: All my tests below were run with this setting ON - I don't know what bugs might re-appear if this setting was OFF_.

![UCheck v5_5_0_0 BETA4 Setings General Launch New Scan at Start 04 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/2eed6dbc-1e2e-43e0-a9bc-1a5642a6bcd5)

**Problem 2**: FIXED - When I turn winget scanning OFF at History & Settings | Scan Settings | Winget | Scan for Updates Using Winget the majority of my "Winget" apps (e.g., Belarc Advisor v12.x, Intel Driver & Support Assistant v24.x, Windows PC Health Check v3.x, etc.) correctly revert to "Community" apps. However, I'm still having problems with my Microsoft .NET (Core) Runtimes (see Problem 4).

**Problem 3**: FIXED - My portable AdwCleaner v8.x is once again detected as a fully supported "Compatible" app. 
______________________________________________

**Problem 4**: I'm still seeing odd behaviour for my **Microsoft .NET (Core) Runtimes**, depending on whether winget scanning is turned ON or OFF at History & Settings | Scan Settings | Winget | Scan for Updates Using Winget.

**Winget Scanning ON**

[Scan Log Winget ON 04 Jun 2024.txt](https://github.com/user-attachments/files/15552477/Scan.Log.Winget.ON.04.Jun.2024.txt)
[Debug Log Winget ON 04 Jun 2024.txt](https://github.com/user-attachments/files/15552482/Debug.Log.Winget.ON.04.Jun.2024.txt)

- Microsoft .NET Core Runtime - 3.1.32 (x64) is correctly identified as a "Winget" app
- **Microsoft Windows Desktop Runtime - 8.0.6 (x64) is displayed as "Unsupported"**

![UCheck v5_5_0_0 BETA4 Winget ON Runtimes Only 04 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/1eeaa1d5-f43e-46e6-a084-1521df475358)

- Both apps are listed in the SCAN log

```
Microsoft .NET Core Runtime - 3.1.32 (x64) (32 bits), version 3.1.32.31915
  [+] Uninstall           : HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{784973c8-d618-4ac8-97ed-1fd52c5bdf2f}

Microsoft Windows Desktop Runtime - 8.0.6 (x64) (32 bits), version 8.0.6.33720
  [+] Uninstall           : HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{942f6911-1a02-4186-8c4c-b27eb2b9733d}
```
- Only Microsoft .NET Core Runtime - 3.1.32 (x64) is listed in the DEBUG log

```
024/06/04 06:21:14:DEBUG	[UCheck::LookupWingetDataImpl] Found exact match candidate for Winget, taking it: Name=Microsoft .NET Core Runtime - 3.1.32 (x64), P=Microsoft .NET Core Runtime - 3.1.32 (x64)
```



**Winget Scanning OFF**

[Scan Log Winget OFF 04 Jun 2024.txt](https://github.com/user-attachments/files/15552486/Scan.Log.Winget.OFF.04.Jun.2024.txt)
[Debug Log Winget OFF 04 Jun 2024.txt](https://github.com/user-attachments/files/15552490/Debug.Log.Winget.OFF.04.Jun.2024.txt)

- **Microsoft .NET Core Runtime - 3.1.32 (x64) incorrectly changes from "Winget" to "Unsupported" instead of "Community"**
- **Microsoft Windows Desktop Runtime - 8.0.6 (x64) is still "Unsupported"**

![UCheck v5_5_0_0 BETA4 Winget OFF Runtimes Only 04 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/d4487795-7b7e-4691-bdc6-23a3030daa51)

- Both apps are listed in the SCAN log (as above when winget scanning is ON)
- Both apps are missing in the DEBUG log

**Comment by ljmacri** [comment]
> **Problem 1**: FIXED - Scans are much more consistent when the new setting at History & Settings | General | Auto-Scan is set to Automatically Launch a Scan When Application Starts

Hi Tigzy:

One additional comment about the **Auto-Scan** setting in UCheck v5.5.0.0-BETA4.

Your choice to use "mutually exclusive" toggle switches for the Auto-Scan feature seems like an odd design choice.

![UCheck v5_5_0_0 BETA4 Setings General Launch New Scan at Start 04 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/97e1881e-d5c5-429a-823a-7a7aa51c0f21)

If the user only has two choices now in v5.5.0.0 (i.e., start a new scan or load the previous scan) I'd prefer to see a **single toggle switch** labelled "Automatically load last scan when application starts" that is OFF by default. When OFF UCheck would automatically launch a scan when the application starts (my preferred default behavior); when ON UCheck would automatically load the last scan when the application starts.

Ideally you would be using **radio buttons** for these two options but I seem to recall you said that the software you use to design the UCheck interface dos not allow radio buttons.

**Comment by Tigzy** [comment]
Hi, could you tell me if some issues are still unfixed by the recent stable release ?

**Comment by ljmacri** [comment]
> _Hi, could you tell me if some issues are still unfixed by the recent stable release ?_

Hi Tigzy:

Problem  # 4 that I documented in my 04-Jun-2024 post <[above](https://github.com/AdliceSoftware/UCheck/issues/52#issuecomment-2147643067)> for my **Microsoft .NET (Core) Runtimes** persists in UCheck v5.5.0.1 (Stable).   I don't have .NET  Runtime 6.0.x, 7.0.x or 9.0.x installed but I assume the same problem occurs for those .NET Runtimes as well.

I currently have Microsoft .NET Core Runtime v3.1 and Microsoft Windows Desktop Runtime v8.0 (which includes the Microsoft .NET Runtime v8.0) installed on my computer, and the **winget list --name Runtime** command shows both are supported by winget.

![Win 10 Pro v22H2 Command Prompt winget_list Runtime Only 14 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/34b35f46-9a10-4eb2-aa2d-7ef34abf8b3c)

When **winget scanning is turned ON** at History & Settings | Scan Settings | Winget | Scan I expect both to be detected as "Winget" apps.  _Instead, only Microsoft .NET Core Runtime v3.1 is a "Winget" app; Microsoft Windows Desktop Runtime v8.0 is "Unsupported"_.

![UCheck v5_5_0_1 Installed Winget Scan ON Runtime Only EDITED 14 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/5889e751-ff9e-4613-aef9-6335b84952f9)

When **winget scanning is turned OFF** I expect both to be detected as "Community" apps (as shown below for the Microsoft Edge WebView2 Runtime). _Instead, both are "Unsupported"_.

![UCheck v5_5_0_1 Installed Winget Scan OFF Runtime Only EDITED 14 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/bb33fd9d-42ef-493e-af8e-1a1cd8f9063b)

From [QuickInstaller](https://www.quickinstaller.net/):

![QuickInstaller v0_3_8859_20616 Runtime Only 14 Jun 2024](https://github.com/AdliceSoftware/UCheck/assets/145856101/3090d5c5-51e3-4cfb-ab2d-2f5f599a53d1)

----------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4529 * Firefox v127.0.0 * Microsoft Defender v4.18.24050.7-1.1.24050.5 * Malwarebytes Premium v5.1.5.116-1.0.1252 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) 0.3.8859.20616 * UCheck Free Portable v5.5.0.1

**Comment by ljmacri** [comment]
> _Problem # 4 that I documented in my 04-Jun-2024 post <[above](https://github.com/AdliceSoftware/UCheck/issues/52#issuecomment-2147643067)> for my **Microsoft .NET (Core) Runtimes** persists in UCheck v5.5.0.1 (Stable). I don't have .NET Runtime 6.0.x, 7.0.x or 9.0.x installed but I assume the same problem occurs for those .NET Runtimes as well_.
> 
Hi @Tigzy

There has been a minor change in the way that the latest **UCheck v5.5.0.2** (rel. 18-Jun-2024) detects my **Microsoft .NET (Core) Runtimes**.

I currently have Microsoft .NET Core Runtime v3.1 and Microsoft Windows Desktop Runtime v8.0 (which includes the Microsoft .NET Runtime v8.0) installed on my computer, and the **winget list --name Runtime** command still shows both are supported by winget.

![Win 10 Pro v22H2 Command Prompt winget_list Runtime Only 21 Jul 2024](https://github.com/user-attachments/assets/3119554c-e23f-4777-b463-cd77d7910eda)

Unlike previous versions of UCheck, however, it doesn't matter now if I have the setting at History & Settings | Scan Settings | Winget | Scan for Updates Using Winget turned ON or OFF - **both my .NET (Core) Runtimes are always "Unsupported"** apps.

In contrast, my Microsoft Edge WebView2 Runtime is correctly identified as a "**Winget**" app if Winget scanning is turned ON, and as a "**Community**" app if Winget scanning is turned OFF, which is the expected behaviour.

![UCheck v5_5_0_2 Installed Winget Scan ON Runtime Only 21 Jul 2024](https://github.com/user-attachments/assets/e567033a-87d1-401a-927c-66aa58c20d18)

![UCheck v5_5_0_2 Installed Winget Scan OFF Runtime Only 21 Jul 2024](https://github.com/user-attachments/assets/92847e5e-d290-4664-9fca-de76d7126d89)
---------------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.4651 * Firefox v128.0.0 * Microsoft Defender v4.18.24060.7-1.1.24060.5 * Malwarebytes Premium v5.1.6.117-1.0.1280 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) 0.3.8859.20616 * UCheck Free Portable v5.5.0.2

**Comment by ljmacri** [comment]
Hi Tigzy:

Further to **Problem 4: Installed "Winget" Apps With Longer Program Names Are Now "Unsupported"** documented in my original post:

I ran a scan today with the latest UCheck Free Portable **v5.7.1.0** (rel. 14-Oct-2024) and all my Winget apps with longer names (including my Microsoft Visual C++ Redistributables and Microsoft .NET Runtime v8.0.x) are no longer classified as Unsupported.

Kudos for the fix. I believe you can now mark this bug report #52 as **Closed** since all four problems I documented for UCheck v5.5.0.0 have been resolved.

![UCheck v5_7_1_0 Installed Tab  MS Visual C++ Redistributables and  NET Runtime v8_0 14 Oct 2024](https://github.com/user-attachments/assets/d5459422-48c3-4889-97ba-6855ad533073)

-----------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.5011 * Firefox v131.0.3 * Microsoft Defender v4.18.24080.9-1.1.24080.9 * Malwarebytes Premium v5.1.11.133-1.0.5048 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck Free Portable 64-bit v5.7.1.0

**Comment by ljmacri** [comment]
Hi Tigzy:

Further to **Problem 4: Installed "Winget" Apps With Longer Program Names Are Now "Unsupported"** documented in my original post:

Sadly, I spoke too soon when I asked to have this issue closed.

I ran a new UCheck v5.7.1.0 scan today (15-Oct-2024) and the two Microsoft Visual C++ 2015-2022 Redistributables that were detected yesterday as Outdated (Type = Winget, Installed, Outdated) are **now Unsupported again**.

Here are scan logs for both days as well as an excerpt from my debug log.

[UCheck v5_7_1_0 Scan Log Two MS Visual C++ 2015-2022 Redistributable Detections 14 Oct 2024.txt](https://github.com/user-attachments/files/17379072/UCheck.v5_7_1_0.Scan.Log.Two.MS.Visual.C%2B%2B.2015-2022.Redistributable.Detections.14.Oct.2024.txt)
[UCheck v5_7_1_0 Scan Log No MS Visual C++ 2015-2022 Redistributable Detections 15 Oct 2024.txt](https://github.com/user-attachments/files/17379073/UCheck.v5_7_1_0.Scan.Log.No.MS.Visual.C%2B%2B.2015-2022.Redistributable.Detections.15.Oct.2024.txt)
[UCheck v5_7_1_0 Debug Logs 14 and 15 Oct 2024.txt](https://github.com/user-attachments/files/17379077/UCheck.v5_7_1_0.Debug.Logs.14.and.15.Oct.2024.txt)

![UCheck v5_7_1_0 Not Detecting Visual C++ 2015-2022 Redistributables 15 Oct 2024](https://github.com/user-attachments/assets/68acc7f0-6a4c-433a-b2cb-4cd973489ffb)

Winget list of all Visual C++ Redistributables (_after 32-bit and 64-bit Visual C++ 2015-2022 Redistributables updated with Winget from command prompt using **winget upgrade --all** command_):

![Win 10 Pro v22H2 Winget List of All MS Visual C++ Redistributables 15 Oct 2024](https://github.com/user-attachments/assets/f923991c-0430-4e98-97da-b799c855600c)
-----------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.5011 * Firefox v131.0.3 * Microsoft Defender v4.18.24080.9-1.1.24080.9 * Malwarebytes Premium v5.1.11.133-1.0.5048 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck Free Portable 64-bit v5.7.1.0

**Comment by Tigzy** [comment]
Yes this is more a Winget limitation than a bug unfortunately. 
Winget trims the end of long names, and if by chance (negatively) there's several software with similar names then UCheck will choose to NO Tsupport them with Winget. 
I'm closing since it's a known limitation that is linked to Winget. We have no real choice than waiting for them to fix that

**Comment by ljmacri** [comment]
> _Yes this is more a Winget limitation than a bug unfortunately. Winget trims the end of long names, and if by chance (negatively) there's several software with similar names then UCheck will choose to NO Tsupport them with Winget. I'm closing since it's a known limitation that is linked to Winget. We have no real choice than waiting for them to fix that_

Hi Tigzy:

Are you using the longer winget full **Name** instead of the shorter **ID**?  My first image in my 15-Oct-2024 post [above](https://github.com/AdliceSoftware/UCheck/issues/52#issuecomment-2413962785) shows UCheck Free Portable v5.7.1.0 classifying my 32-bit and 64-bit Microsoft Visual C++ **2015-2022** Redistributables as **Unsupported**, but QuickInstaller is able to detect available updates for these applications.

![QuickInstaller v0_3_8859_20616 Winget Apps With Longer Names OK EDITED 31 May 2024](https://github.com/user-attachments/assets/05fc8913-0b41-4185-94cc-f863c98a1476)
-----------
Dell Inspiron 15 5584 * 64-bit Win 10 Pro v22H2 build 19045.5011 * Firefox v132.0.0 * Microsoft Defender v4.18.24080.9-1.1.24080.9 * Malwarebytes Premium v5.2.0.140-1.0.5073 * Macrium Reflect Free v8.0.7783 * QuickInstaller (Preview) v0.3.8859.20616 * UCheck Free Portable 64-bit v5.7.1.0
